// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUkJhsEHR5dgvLs-JZS5UEi2SqP0o1JMs',
    appId: '1:603167985609:web:e4be8e0f229171603c2218',
    messagingSenderId: '603167985609',
    projectId: 'handongsell',
    authDomain: 'handongsell.firebaseapp.com',
    storageBucket: 'handongsell.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Ji-BN6vGOQfix_LXWIqIJD8E1a2Sm50',
    appId: '1:603167985609:android:eafa4609b8baf1443c2218',
    messagingSenderId: '603167985609',
    projectId: 'handongsell',
    storageBucket: 'handongsell.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXPAD0oMnN1cV9oTGgVmW-Fl6oUcsmxl8',
    appId: '1:603167985609:ios:2c42dc02a5430b6b3c2218',
    messagingSenderId: '603167985609',
    projectId: 'handongsell',
    storageBucket: 'handongsell.appspot.com',
    iosClientId: '603167985609-13v3rcovrb0h93rdm8or5aeteatoe0k8.apps.googleusercontent.com',
    iosBundleId: 'com.example.moappTeamprj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXPAD0oMnN1cV9oTGgVmW-Fl6oUcsmxl8',
    appId: '1:603167985609:ios:2c42dc02a5430b6b3c2218',
    messagingSenderId: '603167985609',
    projectId: 'handongsell',
    storageBucket: 'handongsell.appspot.com',
    iosClientId: '603167985609-13v3rcovrb0h93rdm8or5aeteatoe0k8.apps.googleusercontent.com',
    iosBundleId: 'com.example.moappTeamprj',
  );
}
